[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "rag-chatbot-backend"
version = "0.1.0"
description = "RAG Chatbot Backend"
requires-python = "==3.12.*"

dependencies = [
    "fastapi[standard]",
    "python-multipart",
    "pymongo",
    "python-dotenv",
    "bcrypt",
    "pypdf",
    "requests"
]

[tool.fastapi]
entrypoint = "backend.main:app"

[tool.setuptools]
py-modules = ["main", "auth", "db"]