[project]
name = "rag-chatbot-backend"
version = "0.1.0"
description = "RAG Chatbot Backend"
requires-python = ">=3.14,<3.15"

dependencies = [
    "fastapi>=0.115",
"uvicorn>=0.30",
    "python-multipart",
    "pymongo",
    "python-dotenv",
    "bcrypt",
    "pypdf",
    "requests"
]

[tool.fastapi]
entrypoint = "main:app"